import Head from "next/head";
import Inner from "@/components/Layout/Inner";
import HomeIndex from "./_components";
export default function Home() {
  return (
    <div>
      <Head>
        <title>LAUNCH APP</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Inner>
        <HomeIndex />
      </Inner>
    </div>
  );
}
