import Head from "next/head";
import { Quantico } from "next/font/google";
const karla = Quantico({
  subsets: ["latin"],
  variable: "--font-karla",
  display: "swap",
  weight: ["400","700" ],
});
import Inner from "@/components/Layout/Inner";
import HomeIndex from "./(Home)/_components";
export default function Home() {
  return (
    <div className={`${karla.variable}`}>
      <Head>
        <title>NMWO PROJECT</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          rel="icon"
          href="/profile_6.jpg"
          style={{ width: "60px", height: "60px", borderRadius: "50%" }}
        />
      </Head>
      <Inner>
        <HomeIndex />
      </Inner>
    </div>
  );
}
